### ISSUE TITLE
copy_and_edit.py to replace a command in a file?

### ISSUE THREAD

**Issue by orschiro** [ubuntu/snappy-playpen#148]
Dear all, 

Coming from this [1] discussion, how can I apply the plugin copy_and_edit.py [2] to replace all instances of `lqrelease-qt5` with `lqrelease` in a specfic build file of a package [3] that I want to create using Snap?

Any help would be very appreciated!

Thankfully,

~Robert

[1] https://askubuntu.com/questions/794875/snapcraft-autoreconf-configure-ac-or-configure-in-is-required/794979?noredirect=1#comment1197730_794979
[2] https://github.com/ubuntu/snappy-playpen/blob/master/ubuntukylin-icon-theme/parts/plugins/copy_and_edit.py
[3] https://gist.github.com/orschiro/489710764173788d07c00b5a84ddaafe

**Comment by dholbach** [comment]
@fcole90 can you maybe help out here?

**Comment by fcole90** [comment]
Hi, the plugin was actually created by @caldav. You can see an example here: https://gist.github.com/caldav/9f0978ef0aa4cda6d4cdf92fced1e99b

I think something like this should work:
```
plugin: copy_and_edit
        source: https://github.com/vkohaupt/vokoscreen/archive/2.5.0.tar.gz
        source-type: git
        files:
            #src/* : dest/*
        edit:
            #src/my-build-file:
                "lqrelease-qt5": "lqrelease"
```

**Comment by orschiro** [comment]
Thank you, @fcole90!

I am not sure if I understood your comment correctly but this is what I tried:

```
name: vokoscreen
version: "2.5.0"
summary: Vokoscreen Screencast Software
description: Snap package for Vokoscreen Screencast Software
  https://gist.github.com/orschiro/489710764173788d07c00b5a84ddaafe
  Currently, you have to manually replace all instances of
  lrelease-qt5 with lrelease in parts/vokoscreen/src/vokoscreen.pro
confinement: strict

apps:
  vokoscreen:
    command: vokoscreen

parts:
  vokoscreen:
    plugin: qmake
      qt-version: qt5
      source: https://github.com/vkohaupt/vokoscreen/archive/2.5.0.tar.gz
    plugin: copy_and_edit
        source: https://github.com/vkohaupt/vokoscreen/archive/2.5.0.tar.gz
        source-type: git
        files:
            #src/* : dest/*
        edit:
            #src/my-build-file:
                "lqrelease-qt5": "lqrelease"
```

Resulting in the following error:

```
Issues while validating snapcraft.yaml: mapping values are not allowed here on line 16 of snapcraft.yam
```
